name: ptc_erp_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # WebView plugin for embedding web content
  # webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  
  # Provider for state management
  provider: ^6.1.2
  
  # HTTP client for API calls
  dio: ^5.8.0+1
  
  # Local storage for saving user credentials
  shared_preferences: ^2.2.2
  
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.5.0
  
  # ObjectBox for local database
  objectbox: ^4.3.1
  objectbox_flutter_libs: any
  
  # File downloading and path handling
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_file: ^3.3.2
  
  # PDF and image viewing
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  url_launcher: ^6.3.2

  connectivity_plus: ^7.0.0
  get_it: ^8.0.2
  injectable: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # ObjectBox generator
  build_runner: ^2.4.12
  objectbox_generator: ^4.3.1

  # Code generation for assets
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: "^0.14.4"
  injectable_generator: ^2.6.2

flutter_gen:
  output: lib/resources/generated
  line_length: 160
  assets:
    enabled: true

objectbox:
  output_dir: resources/objectbox

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

